In [1]:
import pandas as pd

data = {
    "city": ["Ahmedabad", "Ahmedabad", "Ahmedabad",
             "Mumbai", "Mumbai", "Mumbai",
             "Delhi", "Delhi", "Delhi"],

    "product": ["Laptop", "Mobile", "Laptop",
                "Laptop", "Mobile", "Mobile",
                "Laptop", "Mobile", "Laptop"],

    "sales": [50000, 20000, 55000,
              60000, 25000, 30000,
              52000, 22000, 58000]
}

df = pd.DataFrame(data)

print(df)


pd.pivot_table(
    df,
    index="city",
    columns="product",
    values="sales",
    aggfunc="mean"
)

        city product  sales
0  Ahmedabad  Laptop  50000
1  Ahmedabad  Mobile  20000
2  Ahmedabad  Laptop  55000
3     Mumbai  Laptop  60000
4     Mumbai  Mobile  25000
5     Mumbai  Mobile  30000
6      Delhi  Laptop  52000
7      Delhi  Mobile  22000
8      Delhi  Laptop  58000

product     Laptop   Mobile
city
Ahmedabad  52500.0  20000.0
Delhi      55000.0  22000.0
Mumbai     60000.0  27500.0

In [26]:

data = {
    "name": ["A", "B", "C", "D", "E", "F", "G", "H"],
    "city": [
        "Ahmedabad", "Ahmedabad", "Ahmedabad",
        "Mumbai", "Mumbai",
        "Delhi", "Delhi", "Delhi"
    ],
    "score": [80, 90, 70, 60, 80, 90, 70, 80]
}

df = pd.DataFrame(data)

print(df)

  name       city  score
0    A  Ahmedabad     80
1    B  Ahmedabad     90
2    C  Ahmedabad     70
3    D     Mumbai     60
4    E     Mumbai     80
5    F      Delhi     90
6    G      Delhi     70
7    H      Delhi     80

In [20]:
df.groupby("city")

In [21]:
df.groupby("city")["score"].median()

city
Ahmedabad    80.0
Delhi        80.0
Mumbai       70.0
Name: score, dtype: float64

In [22]:
df.groupby("city")["city"].median()

TypeError: dtype 'str' does not support operation 'median'

In [23]:
df.groupby("city")["score"].agg(["mean", "max", "count", "median"])

           mean  max  count  median
city
Ahmedabad  80.0   90      3    80.0
Delhi      80.0   90      3    80.0
Mumbai     70.0   80      2    70.0

In [13]:
df.groupby("city").agg({
"score": "mean",
# "age": "max",
"name": "count",
})

           score  name
city
Ahmedabad   80.0     3
Delhi       80.0     3
Mumbai      70.0     2

In [24]:
df.groupby("city")["score"].mean().sort_values(ascending=False)

city
Ahmedabad    80.0
Delhi        80.0
Mumbai       70.0
Name: score, dtype: float64

In [15]:
df.pivot_table(
values="sales",
index="region", # rows
columns="product", # columns
aggfunc="sum", # how to combine
fill_value=0, # replace missing combos with 0
)

KeyError: 'sales'